// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.SMS.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.SMS;
    using Lykke.Service.SMS.Client;
    using Lykke.Service.SMS.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SmsRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the SmsRequestModel class.
        /// </summary>
        public SmsRequestModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SmsRequestModel class.
        /// </summary>
        public SmsRequestModel(string phoneNumber = default(string), string message = default(string))
        {
            PhoneNumber = phoneNumber;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
